# Generated by Django 5.0.3 on 2024-04-02 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default=django.utils.timezone.now, max_length=100)),
                ('temperature', models.FloatField()),
                ('pHValue', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('water_level_sensor', models.FloatField()),
                ('moisture_sensor', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorous', models.FloatField()),
                ('potassium', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
